title:            "On Scalability"
description:      "Engineering for growth"
logo:             on-scalability-logo.png
disqus_shortname: onscalability
# Assign a default image for your site's header and footer
default_bg:       default_bg.jpg
imagecredit:   country_boy_shane
imagecreditlink: https://www.flickr.com/people/shanegorski/
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Turn on or off the fin animations in the header and footer
triangleheader:		false
animated_fins:	  false
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:       		    http://www.onscalability.com
baseurl:			    http://www.onscalability.com
imageurl:         http://res.cloudinary.com/edgethoughts/image/fetch/f_auto,q_90/http://www.onscalability.com
bgimageurl:       http://res.cloudinary.com/edgethoughts/image/fetch/f_auto,q_60/http://www.onscalability.com
galleryimageurl:  http://res.cloudinary.com/edgethoughts/image/fetch/f_auto,w_770,q_90/http://www.onscalability.com
mgalleryimageurl: http://res.cloudinary.com/edgethoughts/image/fetch/f_auto,w_450,q_90/http://www.onscalability.com
avatarimageurl:   http://res.cloudinary.com/edgethoughts/image/fetch/f_auto,w_150,q_90/http://www.onscalability.com
logoimageurl:     http://res.cloudinary.com/edgethoughts/image/fetch/f_auto,w_280,q_90/http://www.onscalability.com

# Owner/author information
owner:
  name:           Roja Buck
  avatar:         hmfaysal.jpg
  email:          roja@onscalability.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Roja Buck is Chief Architect at <a href="Http://www.Vouchercloud.com">vouchercloud</a> based in Bristol, UK. <br> He spends his time engineering platforms and products used by millions of people.
  # Social networking links used in footer. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:        rojabuck
  facebook:       rojabuck
  github:         roja
  stackexchange:  http://stackoverflow.com/users/217244/roja
  linkedin:       https://www.linkedin.com/in/rojabuck
  instagram:      
  flickr:         
  tumblr:         
  hmfaysalsocial: 
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      tJMxWR7Sc17ftSh7g2UTCVm2br2XGeHbF5yhIf5jLEo
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: categories
    url: /categories
  - title: tags
    url: /tags
  - title: about
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    6
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   :title.html

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://www.onscalability.com'
  relativeLinks: 'http://www.onscalability.com/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "type"
        field:
          element: "select"
          label: "Select Post Type"
          placeholder: "Choose your type"
          options:
            - name: "Standard"
              value: 
            - name: "Quote"
              value: quote
            - name: "Status"
              value: status
            - name: "Photo"
              value: photo
            - name: "Video"
              value: video
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Web-Development"
              value: webdevelopment
            - name: "Interesting"
              value: interesting
            - name: "Status"
              value: status
            - name: "Quotes"
              value: quotes
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "imagecredit"
        field:
          element: "text"
          label: "Image Credit"
          placeholder: "some guy"
      - name: "imagecreditlink"
        field:
          element: "text"
          label: "Credit link for the image"
          placeholder: "http://somewebsite.com"
      - name: "video"
        field:
          element: "text"
          label: "Insert Youtube Link"
          placeholder: "http://youtube.com/somevideo"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
